name: mercure_client
description: Provide a quick way to publish and consume messages on Mercure
version: 1.1.0
homepage: https://github.com/herveGuigoz/mercure_client

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  test: ^1.25.2
